/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FooterNav: typeof import('./components/FooterNav.vue')['default']
    HeaderNav: typeof import('./components/HeaderNav.vue')['default']
    IconPixelarticonsHome: typeof import('~icons/pixelarticons/home')['default']
    IconPixelClose: typeof import('~icons/pixelarticons/close')['default']
    IconPixelHome: typeof import('~icons/pixelarticons/home')['default']
    IconPixelMenu: typeof import('~icons/pixelarticons/menu')['default']
    PickBtn: typeof import('./components/base/PickBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
