/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DialogContainer: typeof import('./components/DialogContainer.vue')['default']
    HomeHero: typeof import('./components/HomeHero.vue')['default']
    IconPixelArrowBarLeft: typeof import('~icons/pixelarticons/arrow-bar-left')['default']
    IconPixelArrowDown: typeof import('~icons/pixelarticons/arrow-down')['default']
    IconPixelArrowLeft: typeof import('~icons/pixelarticons/arrow-left')['default']
    IconPixelArrowRight: typeof import('~icons/pixelarticons/arrow-right')['default']
    IconPixelArrowUp: typeof import('~icons/pixelarticons/arrow-up')['default']
    IconPixelarticonsHome: typeof import('~icons/pixelarticons/home')['default']
    IconPixelClose: typeof import('~icons/pixelarticons/close')['default']
    IconPixelCopy: typeof import('~icons/pixelarticons/copy')['default']
    IconPixelDownasaur: typeof import('~icons/pixelarticons/downasaur')['default']
    IconPixelEye: typeof import('~icons/pixelarticons/eye')['default']
    IconPixelEyeClosed: typeof import('~icons/pixelarticons/eye-closed')['default']
    IconPixelGithub: typeof import('~icons/pixelarticons/github')['default']
    IconPixelHome: typeof import('~icons/pixelarticons/home')['default']
    IconPixelMenu: typeof import('~icons/pixelarticons/menu')['default']
    IconPixelReload: typeof import('~icons/pixelarticons/reload')['default']
    IconPixelSort: typeof import('~icons/pixelarticons/sort')['default']
    NavFooter: typeof import('./components/NavFooter.vue')['default']
    NavHeader: typeof import('./components/NavHeader.vue')['default']
    NumKeyboard: typeof import('./components/base/NumKeyboard.vue')['default']
    PageHeader: typeof import('./components/PageHeader.vue')['default']
    PBtn: typeof import('./components/base/PBtn.vue')['default']
    PickBtn: typeof import('./components/base/PickBtn.vue')['default']
    PinKeyboard: typeof import('./components/PinKeyboard.vue')['default']
    PKeyboard: typeof import('./components/base/PNumKeyboard.vue')['default']
    PLink: typeof import('./components/base/PLink.vue')['default']
    PLoader: typeof import('./components/base/PLoader.vue')['default']
    PNumKeyboard: typeof import('./components/base/PNumKeyboard.vue')['default']
    Profile: typeof import('./components/Profile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
