/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/contacts': RouteRecordInfo<'/contacts', '/contacts', Record<never, never>, Record<never, never>>,
    '/history': RouteRecordInfo<'/history', '/history', Record<never, never>, Record<never, never>>,
    '/landing': RouteRecordInfo<'/landing', '/landing', Record<never, never>, Record<never, never>>,
    '/profile/': RouteRecordInfo<'/profile/', '/profile', Record<never, never>, Record<never, never>>,
    '/profile/create': RouteRecordInfo<'/profile/create', '/profile/create', Record<never, never>, Record<never, never>>,
    '/profile/import': RouteRecordInfo<'/profile/import', '/profile/import', Record<never, never>, Record<never, never>>,
    '/settings/': RouteRecordInfo<'/settings/', '/settings', Record<never, never>, Record<never, never>>,
    '/settings/about': RouteRecordInfo<'/settings/about', '/settings/about', Record<never, never>, Record<never, never>>,
    '/settings/appearance': RouteRecordInfo<'/settings/appearance', '/settings/appearance', Record<never, never>, Record<never, never>>,
    '/settings/backup': RouteRecordInfo<'/settings/backup', '/settings/backup', Record<never, never>, Record<never, never>>,
    '/settings/donate': RouteRecordInfo<'/settings/donate', '/settings/donate', Record<never, never>, Record<never, never>>,
    '/settings/help': RouteRecordInfo<'/settings/help', '/settings/help', Record<never, never>, Record<never, never>>,
    '/settings/language': RouteRecordInfo<'/settings/language', '/settings/language', Record<never, never>, Record<never, never>>,
    '/settings/notifications': RouteRecordInfo<'/settings/notifications', '/settings/notifications', Record<never, never>, Record<never, never>>,
    '/settings/security': RouteRecordInfo<'/settings/security', '/settings/security', Record<never, never>, Record<never, never>>,
  }
}
